/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pckgnew;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import org.jpl7.Query;
import org.jpl7.Term;

/**
 *
 * @author pc
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
         Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Searching");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 90, -1));

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 90, -1));

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 90, -1));

        jButton4.setText("Evacuation");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgnew/ThisIsMainImage.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 800));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Query q = new Query("consult('newestestest.pl')");
        q.hasSolution(); 
        
        String qry = "find_path(Floor, Apartment, Path).";
 
        q = new Query(qry);

        //mapping of the  solution when the query has been called
        Map<String, Term>[] res = q.allSolutions(); //output of the query has been added in the map.
            
        JOptionPane.showMessageDialog(this, res[0]);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                        System.exit(0);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Home mp = new Home();
        mp.show();
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Query q = new Query("consult('newestestest.pl')");
        q.hasSolution();         
        String qry = "find_path(Floor, Apartment, Path).";
        q = new Query(qry);

        Term var1 = q.getSolution().get("Floor");
        Term var2 = q.getSolution().get("Apartment");
       
        int javaVar1 = var1.intValue();
        int javaVar2 = var2.intValue();

        Map<String, int[]> adjM = new HashMap<String, int[]>() {{
            put("1,1", new int[] {0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0});
            put("1,2", new int[] {1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0});
            put("1,3", new int[] {0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0});
            put("2,1", new int[] {1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0});
            put("2,2", new int[] {0,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0});
            put("2,3", new int[] {0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0});
            put("3,1", new int[] {0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0});
            put("3,2", new int[] {0,0,0,0,1,0,1,0,1,0,1,0,0,0,0,0,0,0});
            put("3,3", new int[] {0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0});
            put("4,1", new int[] {0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0});
            put("4,2", new int[] {0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,0,0,0});
            put("4,3", new int[] {0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0});
            put("5,1", new int[] {0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0});
            put("5,2", new int[] {0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0});
            put("5,3", new int[] {0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1});
            put("6,1", new int[] {0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0});
            put("6,2", new int[] {0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1});
            put("6,3", new int[] {0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0});
        }};
        
        for (Map.Entry<String, int[]> entry : adjM.entrySet()) {
            String key = entry.getKey();
            int[] value = entry.getValue();

            String Floor=String.valueOf(javaVar1);
            String Apartment=String.valueOf(javaVar2); 
            
            String location = Floor + ","+  Apartment; 

            if(key.equals(location)){
                System.out.println(location);
                    }      
            for (int i = 0; i < 18; i++) {
                if(key.equals(location)){
                    if (value[i] == 1) {
                        int row = i / 3 + 1;
                        int col = i % 3 + 1;
                        JOptionPane.showMessageDialog(this, "Please Evacuate: (" + row + "," + col + ") for  being adjacent to "+ location);
                    }
                }
            }
            System.out.println();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
